name: test decryption

on:
  push:
    branches: ["*"]
    # paths: 
    # - 'Actions/diagram/*'

jobs:
  checkdeccrypt:
    runs-on: ubuntu-latest
    steps:
      - name: checking in
        uses: actions/checkout@v4
      - name: 'shit to do'
        run: | 
          ls
          cat init.md
